"""init

Revision ID: c847cc608f4b
Revises: 
Create Date: 2026-06-13 17:18:30.494870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c847cc608f4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_normalized_url'), 'urls', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=True)
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='scraperstatus'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_runs_status'), 'scraper_runs', ['status'], unique=False)
    op.create_index(op.f('ix_scraper_runs_url_id'), 'scraper_runs', ['url_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('scraper_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_run_id'], ['scraper_runs.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_scraper_run_id'), 'history', ['scraper_run_id'], unique=False)
    op.create_index(op.f('ix_history_url_id'), 'history', ['url_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_run_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_run_id'], ['scraper_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_normalized_url'), 'links', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_links_scraper_run_id'), 'links', ['scraper_run_id'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_scraper_run_id'), table_name='links')
    op.drop_index(op.f('ix_links_normalized_url'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_history_url_id'), table_name='history')
    op.drop_index(op.f('ix_history_scraper_run_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_scraper_runs_url_id'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_status'), table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_normalized_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
